### ISSUE TITLE
svelte dynamic route won't load on page refresh

### ISSUE THREAD

**Issue by givanse** [givanse/givanse#5]
```
{"errorType":"TypeError",
"errorMessage":"Cannot read property 'paths' of undefined",
"trace":[
"TypeError: Cannot read property 'paths' of undefined",
"    at init (/var/task/__render.js:45547:22)",
"    at Object.<anonymous> (/var/task/__render.js:46542:1)",
"    at Module._compile (internal/modules/cjs/loader.js:1085:14)",
"    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)",
"    at Module.load (internal/modules/cjs/loader.js:950:32)",
"    at Function.Module._load (internal/modules/cjs/loader.js:790:12)",
"    at Module.require (internal/modules/cjs/loader.js:974:19)",
"    at require (internal/modules/cjs/helpers.js:93:18)",
"    at _tryRequireFile (/var/runtime/UserFunction.js:63:32)",
"    at _tryRequire (/var/runtime/UserFunction.js:151:20)"]}
```

`npm run preview` doesn't reproduce it

`/var/runtime/UserFunction` this looks like a Netlify stack trace

**Comment by givanse** [comment]
https://github.com/givanse/givanse/commit/d2b6e2528954d5f800921b95bd3c5105d58a8269
